
package hotelCar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarEuropCar", targetNamespace = "CarEuropCar", wsdlLocation = "file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Server/wsdlFiles/CarEuropCar.wsdl")
public class CarEuropCar
    extends Service
{

    private final static URL CAREUROPCAR_WSDL_LOCATION;
    private final static WebServiceException CAREUROPCAR_EXCEPTION;
    private final static QName CAREUROPCAR_QNAME = new QName("CarEuropCar", "CarEuropCar");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Server/wsdlFiles/CarEuropCar.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAREUROPCAR_WSDL_LOCATION = url;
        CAREUROPCAR_EXCEPTION = e;
    }

    public CarEuropCar() {
        super(__getWsdlLocation(), CAREUROPCAR_QNAME);
    }

    public CarEuropCar(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAREUROPCAR_QNAME, features);
    }

    public CarEuropCar(URL wsdlLocation) {
        super(wsdlLocation, CAREUROPCAR_QNAME);
    }

    public CarEuropCar(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAREUROPCAR_QNAME, features);
    }

    public CarEuropCar(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarEuropCar(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarEuropCarPort
     */
    @WebEndpoint(name = "CarEuropCarBinding")
    public CarEuropCarPort getCarEuropCarBinding() {
        return super.getPort(new QName("CarEuropCar", "CarEuropCarBinding"), CarEuropCarPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarEuropCarPort
     */
    @WebEndpoint(name = "CarEuropCarBinding")
    public CarEuropCarPort getCarEuropCarBinding(WebServiceFeature... features) {
        return super.getPort(new QName("CarEuropCar", "CarEuropCarBinding"), CarEuropCarPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAREUROPCAR_EXCEPTION!= null) {
            throw CAREUROPCAR_EXCEPTION;
        }
        return CAREUROPCAR_WSDL_LOCATION;
    }

}
