
package hotelCar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarSixtPort", targetNamespace = "CarSixt")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CarSixtPort {


    /**
     * 
     * @param gcdRequestParamA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CarSixtcalc")
    @WebResult(name = "CarSixtResponse", partName = "CarSixtResponse")
    @Action(input = "CarSixt/CarSixtPort/CarSixtcalcRequest", output = "CarSixt/CarSixtPort/CarSixtcalcResponse")
    public int carSixtcalc(
        @WebParam(name = "GCDRequest_paramA", partName = "GCDRequest_paramA")
        String gcdRequestParamA);

}
