
package hotelCar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelMercurePort", targetNamespace = "HotelMercure")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HotelMercurePort {


    /**
     * 
     * @param gcdRequestParamA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "HotelMercurecalc")
    @WebResult(name = "HotelMercureResponse", partName = "HotelMercureResponse")
    @Action(input = "HotelMercure/HotelMercurePort/HotelMercurecalcRequest", output = "HotelMercure/HotelMercurePort/HotelMercurecalcResponse")
    public int hotelMercurecalc(
        @WebParam(name = "GCDRequest_paramA", partName = "GCDRequest_paramA")
        String gcdRequestParamA);

}
