
package hotelCar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelHiltonPort", targetNamespace = "HotelHilton")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HotelHiltonPort {


    /**
     * 
     * @param gcdRequestParamA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "HotelHiltoncalc")
    @WebResult(name = "HotelHiltonResponse", partName = "HotelHiltonResponse")
    @Action(input = "HotelHilton/HotelHiltonPort/HotelHiltoncalcRequest", output = "HotelHilton/HotelHiltonPort/HotelHiltoncalcResponse")
    public int hotelHiltoncalc(
        @WebParam(name = "GCDRequest_paramA", partName = "GCDRequest_paramA")
        String gcdRequestParamA);

}
