
package hotelCar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelHolidayInnPort", targetNamespace = "HotelHolidayInn")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HotelHolidayInnPort {


    /**
     * 
     * @param gcdRequestParamA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "HotelHolidayInncalc")
    @WebResult(name = "HotelHolidayInn", partName = "HotelHolidayInn")
    @Action(input = "HotelHolidayInn/HotelHolidayInnPort/HotelHolidayInncalcRequest", output = "HotelHolidayInn/HotelHolidayInnPort/HotelHolidayInncalcResponse")
    public int hotelHolidayInncalc(
        @WebParam(name = "GCDRequest_paramA", partName = "GCDRequest_paramA")
        String gcdRequestParamA);

}
