
package webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightHotelCar", targetNamespace = "FlightHotelCar", wsdlLocation = "file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/FlightHotelCar.wsdl")
public class FlightHotelCar
    extends Service
{

    private final static URL FLIGHTHOTELCAR_WSDL_LOCATION;
    private final static WebServiceException FLIGHTHOTELCAR_EXCEPTION;
    private final static QName FLIGHTHOTELCAR_QNAME = new QName("FlightHotelCar", "FlightHotelCar");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/FlightHotelCar.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTHOTELCAR_WSDL_LOCATION = url;
        FLIGHTHOTELCAR_EXCEPTION = e;
    }

    public FlightHotelCar() {
        super(__getWsdlLocation(), FLIGHTHOTELCAR_QNAME);
    }

    public FlightHotelCar(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTHOTELCAR_QNAME, features);
    }

    public FlightHotelCar(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTHOTELCAR_QNAME);
    }

    public FlightHotelCar(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTHOTELCAR_QNAME, features);
    }

    public FlightHotelCar(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightHotelCar(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightHotelCarPort
     */
    @WebEndpoint(name = "FlightHotelCarBinding")
    public FlightHotelCarPort getFlightHotelCarBinding() {
        return super.getPort(new QName("FlightHotelCar", "FlightHotelCarBinding"), FlightHotelCarPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightHotelCarPort
     */
    @WebEndpoint(name = "FlightHotelCarBinding")
    public FlightHotelCarPort getFlightHotelCarBinding(WebServiceFeature... features) {
        return super.getPort(new QName("FlightHotelCar", "FlightHotelCarBinding"), FlightHotelCarPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTHOTELCAR_EXCEPTION!= null) {
            throw FLIGHTHOTELCAR_EXCEPTION;
        }
        return FLIGHTHOTELCAR_WSDL_LOCATION;
    }

}
