
package webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightHotelCarPort", targetNamespace = "FlightHotelCar")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FlightHotelCarPort {


    /**
     * 
     * @param gcdRequestParamA
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FlightHotelCarcalc")
    @WebResult(name = "FlightHotelCar", partName = "FlightHotelCar")
    @Action(input = "FlightHotelCar/FlightHotelCarPort/FlightHotelCarcalcRequest", output = "FlightHotelCar/FlightHotelCarPort/FlightHotelCarcalcResponse")
    public String flightHotelCarcalc(
        @WebParam(name = "GCDRequest_paramA", partName = "GCDRequest_paramA")
        String gcdRequestParamA);

}
