
package hotelMercure;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelMercure", targetNamespace = "HotelMercure", wsdlLocation = "file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/HotelMercure.wsdl")
public class HotelMercure
    extends Service
{

    private final static URL HOTELMERCURE_WSDL_LOCATION;
    private final static WebServiceException HOTELMERCURE_EXCEPTION;
    private final static QName HOTELMERCURE_QNAME = new QName("HotelMercure", "HotelMercure");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/HotelMercure.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELMERCURE_WSDL_LOCATION = url;
        HOTELMERCURE_EXCEPTION = e;
    }

    public HotelMercure() {
        super(__getWsdlLocation(), HOTELMERCURE_QNAME);
    }

    public HotelMercure(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELMERCURE_QNAME, features);
    }

    public HotelMercure(URL wsdlLocation) {
        super(wsdlLocation, HOTELMERCURE_QNAME);
    }

    public HotelMercure(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELMERCURE_QNAME, features);
    }

    public HotelMercure(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelMercure(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelMercurePort
     */
    @WebEndpoint(name = "HotelMercureBinding")
    public HotelMercurePort getHotelMercureBinding() {
        return super.getPort(new QName("HotelMercure", "HotelMercureBinding"), HotelMercurePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelMercurePort
     */
    @WebEndpoint(name = "HotelMercureBinding")
    public HotelMercurePort getHotelMercureBinding(WebServiceFeature... features) {
        return super.getPort(new QName("HotelMercure", "HotelMercureBinding"), HotelMercurePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELMERCURE_EXCEPTION!= null) {
            throw HOTELMERCURE_EXCEPTION;
        }
        return HOTELMERCURE_WSDL_LOCATION;
    }

}
