
package hotelHolidayInn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelHolidayInn", targetNamespace = "HotelHolidayInn", wsdlLocation = "file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/HotelHolidayInn.wsdl")
public class HotelHolidayInn
    extends Service
{

    private final static URL HOTELHOLIDAYINN_WSDL_LOCATION;
    private final static WebServiceException HOTELHOLIDAYINN_EXCEPTION;
    private final static QName HOTELHOLIDAYINN_QNAME = new QName("HotelHolidayInn", "HotelHolidayInn");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/HotelHolidayInn.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELHOLIDAYINN_WSDL_LOCATION = url;
        HOTELHOLIDAYINN_EXCEPTION = e;
    }

    public HotelHolidayInn() {
        super(__getWsdlLocation(), HOTELHOLIDAYINN_QNAME);
    }

    public HotelHolidayInn(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELHOLIDAYINN_QNAME, features);
    }

    public HotelHolidayInn(URL wsdlLocation) {
        super(wsdlLocation, HOTELHOLIDAYINN_QNAME);
    }

    public HotelHolidayInn(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELHOLIDAYINN_QNAME, features);
    }

    public HotelHolidayInn(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelHolidayInn(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelHolidayInnPort
     */
    @WebEndpoint(name = "HotelHolidayInnBinding")
    public HotelHolidayInnPort getHotelHolidayInnBinding() {
        return super.getPort(new QName("HotelHolidayInn", "HotelHolidayInnBinding"), HotelHolidayInnPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelHolidayInnPort
     */
    @WebEndpoint(name = "HotelHolidayInnBinding")
    public HotelHolidayInnPort getHotelHolidayInnBinding(WebServiceFeature... features) {
        return super.getPort(new QName("HotelHolidayInn", "HotelHolidayInnBinding"), HotelHolidayInnPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELHOLIDAYINN_EXCEPTION!= null) {
            throw HOTELHOLIDAYINN_EXCEPTION;
        }
        return HOTELHOLIDAYINN_WSDL_LOCATION;
    }

}
