
package flightHotelCar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelCar", targetNamespace = "HotelCar", wsdlLocation = "file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Server/wsdlFiles/HotelCar.wsdl")
public class HotelCar
    extends Service
{

    private final static URL HOTELCAR_WSDL_LOCATION;
    private final static WebServiceException HOTELCAR_EXCEPTION;
    private final static QName HOTELCAR_QNAME = new QName("HotelCar", "HotelCar");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Server/wsdlFiles/HotelCar.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELCAR_WSDL_LOCATION = url;
        HOTELCAR_EXCEPTION = e;
    }

    public HotelCar() {
        super(__getWsdlLocation(), HOTELCAR_QNAME);
    }

    public HotelCar(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELCAR_QNAME, features);
    }

    public HotelCar(URL wsdlLocation) {
        super(wsdlLocation, HOTELCAR_QNAME);
    }

    public HotelCar(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELCAR_QNAME, features);
    }

    public HotelCar(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelCar(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelCarPort
     */
    @WebEndpoint(name = "HotelCarBinding")
    public HotelCarPort getHotelCarBinding() {
        return super.getPort(new QName("HotelCar", "HotelCarBinding"), HotelCarPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelCarPort
     */
    @WebEndpoint(name = "HotelCarBinding")
    public HotelCarPort getHotelCarBinding(WebServiceFeature... features) {
        return super.getPort(new QName("HotelCar", "HotelCarBinding"), HotelCarPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELCAR_EXCEPTION!= null) {
            throw HOTELCAR_EXCEPTION;
        }
        return HOTELCAR_WSDL_LOCATION;
    }

}
