
package flightHotelCar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TXLFlight", targetNamespace = "TXLFlight", wsdlLocation = "file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/TXLFlight.wsdl")
public class TXLFlight
    extends Service
{

    private final static URL TXLFLIGHT_WSDL_LOCATION;
    private final static WebServiceException TXLFLIGHT_EXCEPTION;
    private final static QName TXLFLIGHT_QNAME = new QName("TXLFlight", "TXLFlight");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/dafarache/NetBeansProjects/DsSys_Assignment2_Client/wsdlFile/TXLFlight.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TXLFLIGHT_WSDL_LOCATION = url;
        TXLFLIGHT_EXCEPTION = e;
    }

    public TXLFlight() {
        super(__getWsdlLocation(), TXLFLIGHT_QNAME);
    }

    public TXLFlight(WebServiceFeature... features) {
        super(__getWsdlLocation(), TXLFLIGHT_QNAME, features);
    }

    public TXLFlight(URL wsdlLocation) {
        super(wsdlLocation, TXLFLIGHT_QNAME);
    }

    public TXLFlight(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TXLFLIGHT_QNAME, features);
    }

    public TXLFlight(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TXLFlight(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TXLFlightPort
     */
    @WebEndpoint(name = "TXLFlightBinding")
    public TXLFlightPort getTXLFlightBinding() {
        return super.getPort(new QName("TXLFlight", "TXLFlightBinding"), TXLFlightPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TXLFlightPort
     */
    @WebEndpoint(name = "TXLFlightBinding")
    public TXLFlightPort getTXLFlightBinding(WebServiceFeature... features) {
        return super.getPort(new QName("TXLFlight", "TXLFlightBinding"), TXLFlightPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TXLFLIGHT_EXCEPTION!= null) {
            throw TXLFLIGHT_EXCEPTION;
        }
        return TXLFLIGHT_WSDL_LOCATION;
    }

}
